first project commit
khadai/mobile-dev-course pull request #1
Opened 2019-09-22 20:02 UTC by khadai

2019-09-24 14:31 UTC, khadai commented
latest version - https://github.com/khadai/mobile-dev-course/tree/first_milestone

2019-09-27 21:49 UTC, nvipash requested changes
First review of Laboratory work #1

General comments:
- strings should be in strings.xml
- small code formatting moments
- access modifies

Everything else is fine 👌

2019-09-27 21:49 UTC, nvipash commented on app/.gitignore
> +/build
цей .gitignore можна прибрати

2019-09-27 21:49 UTC, nvipash commented on app/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
dependencies з тестами нам не потрібні, їх варто прибрати

2019-09-27 21:49 UTC, nvipash commented on app/src/main/java/com/example/fisrtapplication/MainActivity.java
> +
зайва пуста стрічка

2019-09-27 21:49 UTC, nvipash commented on app/src/main/java/com/example/fisrtapplication/MainActivity.java
> +    FirebaseUser mUser;
відсутні модифікатори доступу

2019-09-27 21:49 UTC, nvipash commented on app/src/main/java/com/example/fisrtapplication/SignInActivity.java
> +    FirebaseAuth mAuth;
відсутні модифікатори доступу

2019-09-27 21:49 UTC, nvipash commented on app/src/main/java/com/example/fisrtapplication/SignInActivity.java
> +        findViewById(R.id.sign_up_button).setOnClickListener(v -> {
варто оголосити спочатку так само як і `userSignIn`

2019-09-27 21:49 UTC, nvipash commented on app/src/main/java/com/example/fisrtapplication/SignInActivity.java
> +            email.setError("Enter a valid email");
текст варто тримати у strings.xml та витягувати з нього

2019-09-27 21:49 UTC, nvipash commented on app/src/main/java/com/example/fisrtapplication/SignInActivity.java
> +            password.setError("At least 8 characters");
те саме

2019-09-27 21:49 UTC, nvipash commented on app/src/main/java/com/example/fisrtapplication/SignUpActivity.java
> +    Button signUp;
відсутні модифікатори доступу

2019-09-27 21:49 UTC, nvipash commented on app/src/main/java/com/example/fisrtapplication/SignUpActivity.java
> +
зайва пуста стрічка

2019-09-27 21:49 UTC, nvipash commented on app/src/main/java/com/example/fisrtapplication/SignUpActivity.java
> +        name.setText("");
очищення мало б бути через `getText().clear()`

2019-09-27 21:49 UTC, nvipash commented on app/src/main/java/com/example/fisrtapplication/SignUpActivity.java
> +                }
тут трохи відступи зліва сильно поїхали, якщо IDE так поформатувала, то ок

2019-09-27 21:49 UTC, nvipash commented on app/src/main/res/layout/activity_sign_in.xml
> +        android:hint="Email"
текст варто тримати в strings.xml

2019-09-29 12:54 UTC, khadai commented on app/.gitignore
> +/build
fixed

2019-09-29 12:54 UTC, khadai commented on app/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
fixed

2019-09-29 12:55 UTC, khadai commented
fixed

2019-09-30 16:13 UTC, nvipash commented on app/src/main/java/com/example/fisrtapplication/SignUpActivity.java
> +                .setDisplayName(name.getText().toString()).build();
@khadai ти забув окрім username, ще phone вказати

2019-10-01 21:28 UTC, khadai commented on app/src/main/java/com/example/fisrtapplication/SignUpActivity.java
> +                .setDisplayName(name.getText().toString()).build();
fixed

2019-10-01 21:29 UTC, khadai commented on app/src/main/java/com/example/fisrtapplication/SignUpActivity.java
> +                .setDisplayName(name.getText().toString()).build();
@nvipash

2019-10-17 08:48 UTC, merged